spring:
    config:
        import: 'optional:file:.env[.properties]'

    jpa:
        show-sql: true
        open-in-view: false # Disable Open Session in View to avoid lazy-loading issues outside transactions
        properties:
            hibernate:
                format_sql: true

    data:
        web:
            pageable:
                default-page-size: 10 # Default number of items per page for pagination
                max-page-size: 50 # Maximum allowed items per page

application:
    security:
        jwt:
            secret-key: '${JWT_SECRET}'
            access-expiration-ms: 900000 # Access token expiration (15 minutes)
            refresh-expiration-ms: 604800000 # Refresh token expiration (7 days)

    bootstrap:
        admin:
            enabled: false
            email: '${ADMIN_BOOTSTRAP_USERNAME}'
            password: '${ADMIN_BOOTSTRAP_PASSWORD}'

logging:
    level:
        org:
            springframework:
                security: 'OFF'
                config:
                annotation: null
                authentication:
                    configuration:
                        InitializeUserDetailsBeanManagerConfigurer: ERROR
